/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuditSchema extends BaseModel {
  static $columns = ['auditComment', 'auditableId', 'auditableType', 'createdAt', 'event', 'id', 'metadata', 'newValues', 'oldValues', 'requestId', 'tags', 'tenantId', 'updatedAt', 'userId', 'userType'] as const
  $columns = AuditSchema.$columns
  @column()
  declare auditComment: string | null
  @column()
  declare auditableId: bigint | number
  @column()
  declare auditableType: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare event: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare metadata: any | null
  @column()
  declare newValues: any | null
  @column()
  declare oldValues: any | null
  @column()
  declare requestId: string | null
  @column()
  declare tags: any | null
  @column()
  declare tenantId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string | null
  @column()
  declare userType: string | null
}

export class ComplaintAnswerSchema extends BaseModel {
  static $columns = ['answerDatetime', 'answerText', 'complaintId', 'createdAt', 'formQuestionId', 'id', 'status', 'updatedAt'] as const
  $columns = ComplaintAnswerSchema.$columns
  @column.dateTime()
  declare answerDatetime: DateTime | null
  @column()
  declare answerText: string | null
  @column()
  declare complaintId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare formQuestionId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare status: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ComplaintFileSchema extends BaseModel {
  static $columns = ['complaintId', 'createdAt', 'file', 'id', 'updatedAt'] as const
  $columns = ComplaintFileSchema.$columns
  @column()
  declare complaintId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare file: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ComplaintTrackingUserGroupSchema extends BaseModel {
  static $columns = ['complaintTrackingId', 'id', 'userGroupId'] as const
  $columns = ComplaintTrackingUserGroupSchema.$columns
  @column()
  declare complaintTrackingId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare userGroupId: number | null
}

export class ComplaintTrackingSchema extends BaseModel {
  static $columns = ['approveStatus', 'complaintId', 'countSla', 'createdAt', 'createdBy', 'detail', 'dueDate', 'dueDateExtend', 'file1', 'file2', 'file3', 'file4', 'file5', 'id', 'mode', 'newValues', 'oldValues', 'overdue', 'ownedBy', 'remark', 'status', 'summary', 'trackingStatus', 'updatedAt', 'updatedBy'] as const
  $columns = ComplaintTrackingSchema.$columns
  @column()
  declare approveStatus: number
  @column()
  declare complaintId: number
  @column()
  declare countSla: boolean | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: number
  @column()
  declare detail: string | null
  @column.date()
  declare dueDate: DateTime | null
  @column.date()
  declare dueDateExtend: DateTime | null
  @column()
  declare file1: string | null
  @column()
  declare file2: string | null
  @column()
  declare file3: string | null
  @column()
  declare file4: string | null
  @column()
  declare file5: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare mode: number
  @column()
  declare newValues: any | null
  @column()
  declare oldValues: any | null
  @column()
  declare overdue: number | null
  @column()
  declare ownedBy: number | null
  @column()
  declare remark: string
  @column()
  declare status: number
  @column()
  declare summary: string | null
  @column()
  declare trackingStatus: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare updatedBy: number | null
}

export class ComplaintWitnessSchema extends BaseModel {
  static $columns = ['complaintId', 'createdAt', 'fullName', 'id', 'telephone', 'updatedAt'] as const
  $columns = ComplaintWitnessSchema.$columns
  @column()
  declare complaintId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare fullName: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare telephone: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ComplaintSchema extends BaseModel {
  static $columns = ['code', 'complainantEmail', 'complainantFullName', 'complainantTelephone', 'consent', 'createdAt', 'detail', 'dueDate', 'formCategoryId', 'formId', 'formSubjectId', 'formSubjectOther', 'hasWitness', 'id', 'incidentAt', 'isAnonymous', 'isComplex', 'isSensitive', 'organizationId', 'ownedBy', 'status', 'title', 'updatedAt', 'updatedBy'] as const
  $columns = ComplaintSchema.$columns
  @column()
  declare code: string
  @column()
  declare complainantEmail: string
  @column()
  declare complainantFullName: string
  @column()
  declare complainantTelephone: string
  @column()
  declare consent: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare detail: string
  @column.date()
  declare dueDate: DateTime | null
  @column()
  declare formCategoryId: number | null
  @column()
  declare formId: number | null
  @column()
  declare formSubjectId: number | null
  @column()
  declare formSubjectOther: string
  @column()
  declare hasWitness: boolean
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare incidentAt: DateTime
  @column()
  declare isAnonymous: boolean
  @column()
  declare isComplex: boolean
  @column()
  declare isSensitive: boolean
  @column()
  declare organizationId: number | null
  @column()
  declare ownedBy: number | null
  @column()
  declare status: number
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare updatedBy: number | null
}

export class ConfigSchema extends BaseModel {
  static $columns = ['category', 'createdAt', 'createdBy', 'hint', 'id', 'mode', 'title', 'updatedAt', 'updatedBy', 'validation', 'value'] as const
  $columns = ConfigSchema.$columns
  @column()
  declare category: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: number
  @column()
  declare hint: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare mode: string | null
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare updatedBy: number
  @column()
  declare validation: string
  @column()
  declare value: string
}

export class FormCategorySchema extends BaseModel {
  static $columns = ['createdAt', 'createdBy', 'description', 'id', 'sequence', 'status', 'subTitle', 'title', 'updatedAt', 'updatedBy'] as const
  $columns = FormCategorySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: number
  @column()
  declare description: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare sequence: number
  @column()
  declare status: number
  @column()
  declare subTitle: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare updatedBy: number | null
}

export class FormQuestionSchema extends BaseModel {
  static $columns = ['createdAt', 'createdBy', 'data', 'formId', 'formSectionId', 'hint', 'id', 'sequence', 'status', 'title', 'type', 'updatedAt', 'updatedBy'] as const
  $columns = FormQuestionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: number
  @column()
  declare data: string | null
  @column()
  declare formId: number
  @column()
  declare formSectionId: number | null
  @column()
  declare hint: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare sequence: number
  @column()
  declare status: number
  @column()
  declare title: string
  @column()
  declare type: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare updatedBy: number | null
}

export class FormSectionSchema extends BaseModel {
  static $columns = ['createdAt', 'createdBy', 'description', 'id', 'sequence', 'status', 'title', 'updatedAt', 'updatedBy'] as const
  $columns = FormSectionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: number
  @column()
  declare description: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare sequence: number
  @column()
  declare status: number
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare updatedBy: number | null
}

export class FormSubjectUserGroupSchema extends BaseModel {
  static $columns = ['formSubjectId', 'id', 'step', 'userGroupId'] as const
  $columns = FormSubjectUserGroupSchema.$columns
  @column()
  declare formSubjectId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare step: number
  @column()
  declare userGroupId: number | null
}

export class FormSubjectSchema extends BaseModel {
  static $columns = ['createdAt', 'createdBy', 'description', 'formCategoryId', 'id', 'isOther', 'sequence', 'status', 'subTitle', 'title', 'updatedAt', 'updatedBy'] as const
  $columns = FormSubjectSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: number
  @column()
  declare description: string
  @column()
  declare formCategoryId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isOther: boolean
  @column()
  declare sequence: number
  @column()
  declare status: number
  @column()
  declare subTitle: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare updatedBy: number | null
}

export class FormSchema extends BaseModel {
  static $columns = ['createdAt', 'createdBy', 'formCategoryId', 'id', 'status', 'title', 'updatedAt', 'updatedBy', 'version'] as const
  $columns = FormSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: number
  @column()
  declare formCategoryId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare status: number
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare updatedBy: number | null
  @column()
  declare version: string
}

export class MasterDatumSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'refId', 'refType', 'title', 'updatedAt'] as const
  $columns = MasterDatumSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare refId: number
  @column()
  declare refType: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class OrganizationSchema extends BaseModel {
  static $columns = ['code', 'createdAt', 'createdBy', 'id', 'parentOrganizationId', 'status', 'title', 'type', 'updatedAt', 'updatedBy'] as const
  $columns = OrganizationSchema.$columns
  @column()
  declare code: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare parentOrganizationId: number | null
  @column()
  declare status: number
  @column()
  declare title: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare updatedBy: number | null
}

export class QueueJobSchema extends BaseModel {
  static $columns = ['acquiredAt', 'data', 'dedupAt', 'dedupId', 'dedupTtl', 'error', 'executeAt', 'finishedAt', 'id', 'queue', 'score', 'status', 'workerId'] as const
  $columns = QueueJobSchema.$columns
  @column()
  declare acquiredAt: bigint | number | null
  @column()
  declare data: string
  @column()
  declare dedupAt: bigint | number | null
  @column()
  declare dedupId: string | null
  @column()
  declare dedupTtl: bigint | number | null
  @column()
  declare error: string | null
  @column()
  declare executeAt: bigint | number | null
  @column()
  declare finishedAt: bigint | number | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare queue: string
  @column()
  declare score: bigint | number | null
  @column()
  declare status: string
  @column()
  declare workerId: string | null
}

export class QueueScheduleSchema extends BaseModel {
  static $columns = ['createdAt', 'cronExpression', 'everyMs', 'fromDate', 'id', 'lastRunAt', 'name', 'nextRunAt', 'payload', 'runCount', 'runLimit', 'status', 'timezone', 'toDate'] as const
  $columns = QueueScheduleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare cronExpression: string | null
  @column()
  declare everyMs: bigint | number | null
  @column.dateTime()
  declare fromDate: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare lastRunAt: DateTime | null
  @column()
  declare name: string
  @column.dateTime()
  declare nextRunAt: DateTime | null
  @column()
  declare payload: string
  @column()
  declare runCount: number
  @column()
  declare runLimit: number | null
  @column()
  declare status: string
  @column()
  declare timezone: string
  @column.dateTime()
  declare toDate: DateTime | null
}

export class SessionSchema extends BaseModel {
  static $columns = ['data', 'expiresAt', 'id', 'userId'] as const
  $columns = SessionSchema.$columns
  @column()
  declare data: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare userId: string | null
}

export class UserGroupUserSchema extends BaseModel {
  static $columns = ['id', 'userGroupId', 'userId'] as const
  $columns = UserGroupUserSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare userGroupId: number | null
  @column()
  declare userId: number | null
}

export class UserGroupSchema extends BaseModel {
  static $columns = ['createdAt', 'createdBy', 'description', 'id', 'status', 'title', 'updatedAt', 'updatedBy'] as const
  $columns = UserGroupSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: number
  @column()
  declare description: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare status: number
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare updatedBy: number | null
}

export class UserLogSchema extends BaseModel {
  static $columns = ['action', 'createdAt', 'id', 'ipLocal', 'ipPublic', 'module', 'updatedAt', 'userId'] as const
  $columns = UserLogSchema.$columns
  @column()
  declare action: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare ipLocal: string
  @column()
  declare ipPublic: string
  @column()
  declare module: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class UserModuleActionSchema extends BaseModel {
  static $columns = ['action', 'code', 'createdAt', 'id', 'sequence', 'updatedAt', 'userModuleId'] as const
  $columns = UserModuleActionSchema.$columns
  @column()
  declare action: string
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare sequence: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userModuleId: number | null
}

export class UserModuleSchema extends BaseModel {
  static $columns = ['createdAt', 'cssClass', 'icon', 'id', 'mode', 'module', 'parentModuleId', 'sequence', 'slug', 'status', 'title', 'updatedAt', 'url'] as const
  $columns = UserModuleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare cssClass: string
  @column()
  declare icon: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare mode: string
  @column()
  declare module: string
  @column()
  declare parentModuleId: number | null
  @column()
  declare sequence: number
  @column()
  declare slug: string
  @column()
  declare status: number
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare url: string
}

export class UserRolePermissionSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'updatedAt', 'userModuleActionId', 'userRoleId'] as const
  $columns = UserRolePermissionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userModuleActionId: number | null
  @column()
  declare userRoleId: number
}

export class UserRoleSchema extends BaseModel {
  static $columns = ['createdAt', 'createdBy', 'description', 'id', 'status', 'title', 'updatedAt', 'updatedBy'] as const
  $columns = UserRoleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: number
  @column()
  declare description: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare status: number
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare updatedBy: number | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'createdBy', 'email', 'fullName', 'id', 'loginAt', 'organizationId', 'password', 'status', 'updatedAt', 'updatedBy', 'userRoleId'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: number
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare loginAt: DateTime | null
  @column()
  declare organizationId: number | null
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare status: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare updatedBy: number | null
  @column()
  declare userRoleId: number
}
